name: NoEmotecraft
description: ${description}
main: io.github.kosmx.emotes.bukkit.BukkitWrapper
version: ${version}
api-version: 1.21
website: https://github.com/TheMek0/NoEmotecraft
authors: [KomsX, TheMeko]
depend: [ProtocolLib]
folia-supported: true
