plugins {
    id "java"
    id "maven-publish"
}

dependencies {
    implementation project(":emotesAPI")
    implementation "dev.kosmx.player-anim:anim-core:${project.player_anim_core}"
    compileOnly "com.google.code.gson:gson:2.11.+"
}

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'emotesExecutor'

            artifact(jar)
            artifact(sourcesJar)
            artifact(javadocJar)

            pom.withXml {
                def depsNode = asNode().appendNode("dependencies")

                def animatorNode = depsNode.appendNode("dependency")
                animatorNode.appendNode("groupId", "dev.kosmx.player-anim")
                animatorNode.appendNode("artifactId", "anim-core")
                animatorNode.appendNode("version", project.player_anim_core)
                animatorNode.appendNode("scope", "compile")


                def apiNode = depsNode.appendNode("dependency")
                apiNode.appendNode("groupId", project.group)
                apiNode.appendNode("artifactId", "emotesAPI")
                apiNode.appendNode("version", project.version_base)
                apiNode.appendNode("scope", "compile")
            }

            pom {
                name = "executor"
                description = "Minecraft NoEmotecraft executor interface"
                url = 'https://github.com/TheMek0/NoEmotecraft'
                developers {
                    developer {
                        id = 'kosmx'
                        name = 'KosmX'
                        email = 'kosmx.mc@gmail.com'
                    }
                }

                scm {
                    connection = "scm:git:github.com/themek0/NoEmotecraft.git"
                    developerConnection = "scm:git:github.com/themek0/NoEmotecraft.git"
                    url = "https://github.com/TheMek0/NoEmotecraft"
                }
            }
        }
    }

    repositories {
        mavenLocal()
        mavenCentral()
    }
}