plugins {
    id "java"
    id "maven-publish"
}

project.archivesBaseName = "${project.archives_base_name}-bukkit-${project.version_base}+mc${project.minecraft_version}"

repositories {
    mavenCentral()

    maven {
        url "https://hub.spigotmc.org/nexus/content/repositories/snapshots"
    }
    maven {
        url "https://repo.dmulloy2.net/repository/public/"
    }
}

configurations {
    compileModule

    compileClasspath.extendsFrom compileModule
    runtimeClasspath.extendsFrom compileModule
}

dependencies {
    implementation("org.spigotmc:spigot-api:${project.spigot_api}")
    implementation("com.comphenix.protocol:ProtocolLib:5.3.0")

    compileModule(project(":emotesAPI")) {
        transitive = false
    }
    compileModule(project(":executor")) {
        transitive = false
    }
    compileModule(project(":emotesServer")) {
        transitive = false
    }

    compileModule(project(":emotesAssets")) {
        transitive = false
    }

    compileModule("dev.kosmx.player-anim:anim-core:${project.player_anim_core}") {
        transitive = false
    }
}

processResources {
    inputs.property "version", project.version_base
    inputs.property "description", rootProject.mod_description

    filesMatching("plugin.yml") {
        expand version: project.version_base, description: rootProject.mod_description
    }
}

compileJava {
    dependsOn(":emotesAssets:publicationJar")
}

jar {
    from {
        configurations.compileModule.collect() {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}

tasks.register("copyArtifacts") {
    dependsOn("build")
    doLast {
        copy {
            from "${project.projectDir}/build/libs/${project.archives_base_name}-bukkit-${project.version_base}+mc${project.minecraft_version}.jar"
            into "${rootProject.projectDir}/artifacts"
        }
    }
}

java {
    withSourcesJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'emotesBukkit'

            artifact(jar)
            artifact(sourcesJar)

            pom {
                name = "emotesBukkit"
                description = "Minecraft NoEmotecraft Bukkit plugin"
                url = 'https://github.com/TheMek0/NoEmotecraft'
                developers {
                    developer {
                        id = 'kosmx'
                        name = 'KosmX'
                        email = 'kosmx.mc@gmail.com'
                    }
                }

                scm {
                    connection = "scm:git:github.com/themek0/NoEmotecraft.git"
                    developerConnection = "scm:git:github.com/themek0/NoEmotecraft.git"
                    url = "https://github.com/TheMek0/NoEmotecraft"
                }
            }
        }
    }

    repositories {
        mavenLocal()
    }
}
