plugins {
    id "java"
}

architectury{
    common("fabric")
}

loom{
    accessWidenerPath = file("src/main/resources/emotes.accesswidener")
}

dependencies {
    implementation project(":emotesAssets")
    implementation project(":emotesAPI")
    implementation project(":executor")
    implementation project(":emotesServer")

    modImplementation "io.github.kosmx.bendy-lib:bendy-lib:${project.bendylib_version}"
    modImplementation "dev.kosmx.player-anim:player-animation-lib-fabric:${project.player_anim}"

    modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")
}

compileJava {
    dependsOn(":emotesAssets:publicationJar")
}
